// export const applications = [
//     {
//         id: 1,
//         applicantName: "Ibrahim Chidenna",
//         isVerified: true,
//         rating: 5,
//         ratingCount: 5.0,
//         timePosted: "5 mins ago",
//         jobTitle: "Figma Product Designer - Fintech Mobile App",
//         jobTitleLink: true,
//         salaryRange: "₦500,000 - ₦700,000",
//         description:
//             "Seeking a creative UI designer to craft a clean and uplifting interface for 'Remember Why', an iOS app that motivates users in their weight-loss journey. The role requires a modern, simple, and supportive, focusing on typography and a friendly visual tone. Experience...",
//         tags: ["Senior", "Remote", "1 week"],
//         views: 5,
//         status: "Shortlisted", // "Shortlisted" | "Rejected" | "Pending" | null
//     },
//     {
//         id: 2,
//         applicantName: "Temitope Abiodun",
//         isVerified: true,
//         rating: 3,
//         ratingCount: 3.5,
//         timePosted: "1 hr ago",
//         jobTitle: "Web Developer [Next.js / React + AI Tools]",
//         jobTitleLink: true,
//         salaryRange: "₦250,000",
//         description:
//             "We're looking for a skilled and reliable Web Developer to join our team. You'll work on building and improving web-based tools using modern frameworks and AI-powered development workflows.",
//         tags: ["Intermediate", "Remote", "3 days"],
//         views: 16,
//         status: "Rejected",
//     },
//     {
//         id: 3,
//         applicantName: "Charles Ikenna",
//         isVerified: true,
//         rating: 2,
//         ratingCount: 2.0,
//         timePosted: "2 days ago",
//         jobTitle: "Logo Design and Digitalization for Health Coaching Business",
//         jobTitleLink: true,
//         salaryRange: "₦150,000 - ₦200,000",
//         description:
//             "Seeking a skilled graphic designer to create a hand-drawn logo and create a digital version for a health coaching business. The ideal candidate will have experience in logo design and be proficient in using design software to bring concepts to life.",
//         tags: ["Entry-level", "Remote", "1 week"],
//         views: 23,
//         status: "Rejected",
//     },
//     {
//         id: 4,
//         applicantName: "Amina Okafor",
//         isVerified: true,
//         rating: 4,
//         ratingCount: 4.2,
//         timePosted: "3 days ago",
//         jobTitle: "Mobile App Developer - E-Commerce Platform",
//         jobTitleLink: true,
//         salaryRange: "₦400,000 - ₦600,000",
//         description:
//             "We need a talented mobile developer to build a cross-platform e-commerce app. You will be responsible for implementing user-facing features and ensuring smooth performance across iOS and Android devices.",
//         tags: ["Senior", "Hybrid", "2 weeks"],
//         views: 41,
//         status: "Shortlisted",
//     },
//     {
//         id: 5,
//         applicantName: "David Emeka",
//         isVerified: false,
//         rating: 3,
//         ratingCount: 3.8,
//         timePosted: "4 days ago",
//         jobTitle: "Content Writer - Tech Blog",
//         jobTitleLink: true,
//         salaryRange: "₦80,000 - ₦120,000",
//         description:
//             "Looking for a creative and knowledgeable content writer to produce engaging articles for our tech blog. Must have a good understanding of emerging technologies and be able to write in a clear, accessible tone.",
//         tags: ["Entry-level", "Remote", "Ongoing"],
//         views: 12,
//         status: null,
//     },
//     {
//         id: 6,
//         applicantName: "Fatima Al-Rashid",
//         isVerified: true,
//         rating: 5,
//         ratingCount: 4.9,
//         timePosted: "5 days ago",
//         jobTitle: "Backend Engineer - SaaS Platform",
//         jobTitleLink: true,
//         salaryRange: "₦350,000 - ₦500,000",
//         description:
//             "Join our growing team to build and maintain scalable backend systems. You will design RESTful APIs, optimize database queries, and collaborate with frontend teams to deliver a seamless SaaS experience.",
//         tags: ["Mid-level", "Remote", "1 month"],
//         views: 58,
//         status: "Shortlisted",
//     },
//     {
//         id: 7,
//         applicantName: "Obi Nwankwo",
//         isVerified: true,
//         rating: 2,
//         ratingCount: 2.5,
//         timePosted: "1 week ago",
//         jobTitle: "Data Analyst - Marketing Team",
//         jobTitleLink: true,
//         salaryRange: "₦180,000 - ₦250,000",
//         description:
//             "We are seeking a data analyst to help the marketing team make data-driven decisions. You will analyze campaign performance, build dashboards, and present insights to stakeholders.",
//         tags: ["Intermediate", "On-site", "3 months"],
//         views: 29,
//         status: "Rejected",
//     },
//     {
//         id: 8,
//         applicantName: "Grace Adeyemi",
//         isVerified: true,
//         rating: 4,
//         ratingCount: 4.5,
//         timePosted: "1 week ago",
//         jobTitle: "UI/UX Designer - Dashboard Redesign",
//         jobTitleLink: true,
//         salaryRange: "₦200,000 - ₦350,000",
//         description:
//             "We need a talented UI/UX designer to lead the redesign of our internal dashboard. You will conduct user research, create wireframes, and work closely with developers to bring the new design to life.",
//         tags: ["Mid-level", "Hybrid", "2 weeks"],
//         views: 34,
//         status: null,
//     },
//     {
//         id: 9,
//         applicantName: "Samuel Usman",
//         isVerified: false,
//         rating: 1,
//         ratingCount: 1.5,
//         timePosted: "2 weeks ago",
//         jobTitle: "DevOps Engineer - Cloud Infrastructure",
//         jobTitleLink: true,
//         salaryRange: "₦450,000 - ₦650,000",
//         description:
//             "Looking for an experienced DevOps engineer to manage our cloud infrastructure on AWS. You will set up CI/CD pipelines, manage containerized deployments, and ensure system reliability.",
//         tags: ["Senior", "Remote", "Ongoing"],
//         views: 47,
//         status: "Rejected",
//     },
//     {
//         id: 10,
//         applicantName: "Chidinma Eze",
//         isVerified: true,
//         rating: 4,
//         ratingCount: 4.0,
//         timePosted: "2 weeks ago",
//         jobTitle: "QA Engineer - Mobile Testing",
//         jobTitleLink: true,
//         salaryRange: "₦150,000 - ₦220,000",
//         description:
//             "We need a QA engineer to test our mobile applications across multiple devices. You will write test plans, execute test cases, and work with developers to resolve bugs.",
//         tags: ["Mid-level", "Remote", "1 month"],
//         views: 19,
//         status: "Shortlisted",
//     },
//     {
//         id: 11,
//         applicantName: "Blessing Nwosu",
//         isVerified: true,
//         rating: 3,
//         ratingCount: 3.2,
//         timePosted: "3 weeks ago",
//         jobTitle: "Social Media Manager - Startup",
//         jobTitleLink: true,
//         salaryRange: "₦100,000 - ₦150,000",
//         description:
//             "Join our early-stage startup as a social media manager. You will plan content calendars, grow our online presence, and engage with our community across platforms.",
//         tags: ["Entry-level", "Remote", "Ongoing"],
//         views: 8,
//         status: null,
//     },
//     {
//         id: 12,
//         applicantName: "Emeka Okonkwo",
//         isVerified: true,
//         rating: 5,
//         ratingCount: 5.0,
//         timePosted: "1 month ago",
//         jobTitle: "Full Stack Developer - FinTech Solution",
//         jobTitleLink: true,
//         salaryRange: "₦500,000 - ₦800,000",
//         description:
//             "We are building a next-gen fintech platform and need a full stack developer. You will work on both frontend and backend, integrating payment gateways and ensuring security compliance.",
//         tags: ["Senior", "Hybrid", "3 months"],
//         views: 72,
//         status: "Shortlisted",
//     },
//     {
//         id: 13,
//         applicantName: "Adaeze Igwe",
//         isVerified: false,
//         rating: 2,
//         ratingCount: 2.8,
//         timePosted: "1 month ago",
//         jobTitle: "Graphic Designer - Brand Identity",
//         jobTitleLink: true,
//         salaryRange: "₦120,000 - ₦180,000",
//         description:
//             "We need a graphic designer to help define our brand identity. You will create logos, marketing materials, and social media assets that reflect our modern and approachable brand voice.",
//         tags: ["Entry-level", "Remote", "2 weeks"],
//         views: 15,
//         status: "Rejected",
//     },
//     {
//         id: 14,
//         applicantName: "Kalu Obi",
//         isVerified: true,
//         rating: 4,
//         ratingCount: 4.1,
//         timePosted: "6 weeks ago",
//         jobTitle: "Project Manager - Agile Teams",
//         jobTitleLink: true,
//         salaryRange: "₦300,000 - ₦420,000",
//         description:
//             "Looking for a project manager experienced in Agile methodologies to coordinate cross-functional teams. You will manage timelines, facilitate sprints, and ensure project delivery.",
//         tags: ["Mid-level", "On-site", "Ongoing"],
//         views: 31,
//         status: null,
//     },
//     {
//         id: 15,
//         applicantName: "Ngozi Achike",
//         isVerified: true,
//         rating: 3,
//         ratingCount: 3.6,
//         timePosted: "2 months ago",
//         jobTitle: "Copywriter - Ad Campaign",
//         jobTitleLink: true,
//         salaryRange: "₦90,000 - ₦130,000",
//         description:
//             "We need a copywriter to craft compelling ad copy for an upcoming campaign. You will work with the creative team to develop messaging that drives engagement and conversions.",
//         tags: ["Entry-level", "Remote", "1 week"],
//         views: 10,
//         status: "Rejected",
//     },
// ];

// // Derived summary counts
// export const applicationSummary = {
//     total: applications.length,
//     ongoing: applications.filter(
//         (app) => app.status === null || app.status === "Shortlisted"
//     ).length,
//     completed: applications.filter((app) => app.status === "Completed").length,
//     rejected: applications.filter((app) => app.status === "Rejected").length,
// };


export const applications = [
    {
        id: 1,
        applicantName: "Ibrahim Chidenna",
        isVerified: true,
        rating: 5,
        ratingCount: 5.0,
        timePosted: "5 mins ago",
        jobTitle: "Figma Product Designer - Fintech Mobile App",
        salaryRange: "₦500,000 - ₦700,000",
        description:
            "Seeking a creative UI designer to craft a clean and uplifting interface for 'Remember Why', an iOS app that motivates users in their weight-loss journey. The role requires a modern, simple, and supportive design, focusing on typography and a friendly visual tone.",
        tags: ["Senior", "Remote", "1 week"],
        views: 5,
        status: "Shortlisted",
        // ── expanded detail fields ──
        location: "Lagos, Nigeria (Remote)",
        experience: "3+ years",
        deadline: "Feb 14, 2026",
        responsibilities: [
            "Design end-to-end user flows and high-fidelity Figma prototypes",
            "Conduct user research and usability testing sessions",
            "Collaborate closely with the product manager and iOS developers",
            "Maintain and expand the app's design system",
        ],
        qualifications: [
            "Strong portfolio of mobile UI/UX work",
            "Proficient in Figma with Auto Layout & components",
            "Familiarity with iOS Human Interface Guidelines",
            "Excellent communication and iteration skills",
        ],
    },
    {
        id: 2,
        applicantName: "Temitope Abiodun",
        isVerified: true,
        rating: 3,
        ratingCount: 3.5,
        timePosted: "1 hr ago",
        jobTitle: "Web Developer [Next.js / React + AI Tools]",
        salaryRange: "₦250,000",
        description:
            "We're looking for a skilled and reliable Web Developer to join our team. You'll work on building and improving web-based tools using modern frameworks and AI-powered development workflows.",
        tags: ["Intermediate", "Remote", "3 days"],
        views: 16,
        status: "Rejected",
        location: "Abuja, Nigeria (Remote)",
        experience: "2+ years",
        deadline: "Feb 10, 2026",
        responsibilities: [
            "Build and maintain Next.js applications for internal tooling",
            "Integrate third-party AI APIs into existing workflows",
            "Write clean, well-tested TypeScript code",
            "Participate in code reviews and sprint planning",
        ],
        qualifications: [
            "Hands-on experience with Next.js and React",
            "Comfortable working with REST and GraphQL APIs",
            "Understanding of CI/CD pipelines",
            "Good problem-solving and debugging skills",
        ],
    },
    {
        id: 3,
        applicantName: "Charles Ikenna",
        isVerified: true,
        rating: 2,
        ratingCount: 2.0,
        timePosted: "2 days ago",
        jobTitle: "Logo Design and Digitalization for Health Coaching Business",
        salaryRange: "₦150,000 - ₦200,000",
        description:
            "Seeking a skilled graphic designer to create a hand-drawn logo and create a digital version for a health coaching business. The ideal candidate will have experience in logo design and be proficient in using design software to bring concepts to life.",
        tags: ["Entry-level", "Remote", "1 week"],
        views: 23,
        status: "Rejected",
        location: "Nationwide (Remote)",
        experience: "1+ year",
        deadline: "Feb 20, 2026",
        responsibilities: [
            "Sketch and refine logo concepts based on brand brief",
            "Digitize approved sketches into scalable vector formats",
            "Deliver files in AI, SVG, PNG, and PDF formats",
            "Incorporate feedback through revision rounds",
        ],
        qualifications: [
            "Portfolio demonstrating logo and brand identity work",
            "Proficient in Adobe Illustrator or similar vector tools",
            "Strong understanding of color theory and typography",
            "Ability to translate verbal briefs into visual concepts",
        ],
    },
    {
        id: 4,
        applicantName: "Amina Okafor",
        isVerified: true,
        rating: 4,
        ratingCount: 4.2,
        timePosted: "3 days ago",
        jobTitle: "Mobile App Developer - E-Commerce Platform",
        salaryRange: "₦400,000 - ₦600,000",
        description:
            "We need a talented mobile developer to build a cross-platform e-commerce app. You will be responsible for implementing user-facing features and ensuring smooth performance across iOS and Android devices.",
        tags: ["Senior", "Hybrid", "2 weeks"],
        views: 41,
        status: "Shortlisted",
        location: "Lagos, Nigeria (Hybrid)",
        experience: "4+ years",
        deadline: "Mar 1, 2026",
        responsibilities: [
            "Develop and maintain cross-platform mobile features using React Native",
            "Optimize app performance and reduce load times",
            "Integrate payment gateways and third-party services",
            "Write unit and integration tests for all new features",
        ],
        qualifications: [
            "Strong React Native or Flutter experience",
            "Familiarity with iOS and Android deployment pipelines",
            "Experience integrating payment APIs (Paystack, Flutterwave)",
            "Solid understanding of state management patterns",
        ],
    },
    {
        id: 5,
        applicantName: "David Emeka",
        isVerified: false,
        rating: 3,
        ratingCount: 3.8,
        timePosted: "4 days ago",
        jobTitle: "Content Writer - Tech Blog",
        salaryRange: "₦80,000 - ₦120,000",
        description:
            "Looking for a creative and knowledgeable content writer to produce engaging articles for our tech blog. Must have a good understanding of emerging technologies and be able to write in a clear, accessible tone.",
        tags: ["Entry-level", "Remote", "Ongoing"],
        views: 12,
        status: null,
        location: "Nationwide (Remote)",
        experience: "1+ year",
        deadline: "Ongoing",
        responsibilities: [
            "Research and write 3–4 tech articles per week",
            "Optimize content for SEO using provided keywords",
            "Coordinate with the design team for article visuals",
            "Engage with reader comments and feedback",
        ],
        qualifications: [
            "Strong written communication skills in English",
            "Familiarity with tech topics (AI, cloud, web dev)",
            "Basic SEO knowledge",
            "Ability to meet weekly deadlines consistently",
        ],
    },
    {
        id: 6,
        applicantName: "Fatima Al-Rashid",
        isVerified: true,
        rating: 5,
        ratingCount: 4.9,
        timePosted: "5 days ago",
        jobTitle: "Backend Engineer - SaaS Platform",
        salaryRange: "₦350,000 - ₦500,000",
        description:
            "Join our growing team to build and maintain scalable backend systems. You will design RESTful APIs, optimize database queries, and collaborate with frontend teams to deliver a seamless SaaS experience.",
        tags: ["Mid-level", "Remote", "1 month"],
        views: 58,
        status: "Shortlisted",
        location: "Lagos, Nigeria (Remote)",
        experience: "3+ years",
        deadline: "Mar 5, 2026",
        responsibilities: [
            "Design and implement RESTful and GraphQL APIs",
            "Optimize PostgreSQL queries and schema design",
            "Set up and maintain background job queues",
            "Collaborate with frontend and DevOps on deployments",
        ],
        qualifications: [
            "Proficient in Node.js or Python (FastAPI/Django)",
            "Experience with PostgreSQL and Redis",
            "Understanding of microservices architecture",
            "Familiarity with Docker and AWS basics",
        ],
    },
    {
        id: 7,
        applicantName: "Obi Nwankwo",
        isVerified: true,
        rating: 2,
        ratingCount: 2.5,
        timePosted: "1 week ago",
        jobTitle: "Data Analyst - Marketing Team",
        salaryRange: "₦180,000 - ₦250,000",
        description:
            "We are seeking a data analyst to help the marketing team make data-driven decisions. You will analyze campaign performance, build dashboards, and present insights to stakeholders.",
        tags: ["Intermediate", "On-site", "3 months"],
        views: 29,
        status: "Rejected",
        location: "Abuja, Nigeria (On-site)",
        experience: "2+ years",
        deadline: "Feb 28, 2026",
        responsibilities: [
            "Analyze marketing campaign performance metrics",
            "Build and maintain dashboards in Google Looker or Tableau",
            "Present weekly insights to the marketing leadership",
            "Propose A/B testing strategies and track results",
        ],
        qualifications: [
            "Strong skills in SQL and Python or R",
            "Experience with Google Analytics or similar platforms",
            "Ability to translate data into actionable recommendations",
            "Good presentation and storytelling skills",
        ],
    },
    {
        id: 8,
        applicantName: "Grace Adeyemi",
        isVerified: true,
        rating: 4,
        ratingCount: 4.5,
        timePosted: "1 week ago",
        jobTitle: "UI/UX Designer - Dashboard Redesign",
        salaryRange: "₦200,000 - ₦350,000",
        description:
            "We need a talented UI/UX designer to lead the redesign of our internal dashboard. You will conduct user research, create wireframes, and work closely with developers to bring the new design to life.",
        tags: ["Mid-level", "Hybrid", "2 weeks"],
        views: 34,
        status: null,
        location: "Lagos, Nigeria (Hybrid)",
        experience: "2+ years",
        deadline: "Feb 22, 2026",
        responsibilities: [
            "Lead user research and competitor analysis",
            "Create wireframes, prototypes, and high-fidelity designs",
            "Facilitate design review sessions with stakeholders",
            "Hand off designs to developers with detailed specs",
        ],
        qualifications: [
            "Strong Figma skills with a solid portfolio",
            "Experience designing data-heavy dashboards",
            "Comfortable facilitating workshops and presentations",
            "Familiarity with design systems and component libraries",
        ],
    },
    {
        id: 9,
        applicantName: "Samuel Usman",
        isVerified: false,
        rating: 1,
        ratingCount: 1.5,
        timePosted: "2 weeks ago",
        jobTitle: "DevOps Engineer - Cloud Infrastructure",
        salaryRange: "₦450,000 - ₦650,000",
        description:
            "Looking for an experienced DevOps engineer to manage our cloud infrastructure on AWS. You will set up CI/CD pipelines, manage containerized deployments, and ensure system reliability.",
        tags: ["Senior", "Remote", "Ongoing"],
        views: 47,
        status: "Rejected",
        location: "Nationwide (Remote)",
        experience: "4+ years",
        deadline: "Ongoing",
        responsibilities: [
            "Design and manage AWS infrastructure as code (Terraform)",
            "Build and maintain CI/CD pipelines with GitHub Actions",
            "Manage Docker and Kubernetes clusters",
            "Monitor system health and implement alerting",
        ],
        qualifications: [
            "AWS Solutions Architect or equivalent certification",
            "Hands-on experience with Terraform and Kubernetes",
            "Strong scripting skills (Bash, Python)",
            "Experience with monitoring tools (Datadog, Prometheus)",
        ],
    },
    {
        id: 10,
        applicantName: "Chidinma Eze",
        isVerified: true,
        rating: 4,
        ratingCount: 4.0,
        timePosted: "2 weeks ago",
        jobTitle: "QA Engineer - Mobile Testing",
        salaryRange: "₦150,000 - ₦220,000",
        description:
            "We need a QA engineer to test our mobile applications across multiple devices. You will write test plans, execute test cases, and work with developers to resolve bugs.",
        tags: ["Mid-level", "Remote", "1 month"],
        views: 19,
        status: "Shortlisted",
        location: "Lagos, Nigeria (Remote)",
        experience: "2+ years",
        deadline: "Mar 10, 2026",
        responsibilities: [
            "Write and execute test plans for iOS and Android apps",
            "Set up and maintain automated regression test suites",
            "Log and triage bugs with detailed reproduction steps",
            "Collaborate with developers during sprint reviews",
        ],
        qualifications: [
            "Experience with Appium or Detox for mobile testing",
            "Strong analytical and problem-solving skills",
            "Familiarity with Agile/Scrum workflows",
            "Good documentation and communication skills",
        ],
    },
    {
        id: 11,
        applicantName: "Blessing Nwosu",
        isVerified: true,
        rating: 3,
        ratingCount: 3.2,
        timePosted: "3 weeks ago",
        jobTitle: "Social Media Manager - Startup",
        salaryRange: "₦100,000 - ₦150,000",
        description:
            "Join our early-stage startup as a social media manager. You will plan content calendars, grow our online presence, and engage with our community across platforms.",
        tags: ["Entry-level", "Remote", "Ongoing"],
        views: 8,
        status: null,
        location: "Nationwide (Remote)",
        experience: "1+ year",
        deadline: "Ongoing",
        responsibilities: [
            "Plan and schedule content across Twitter, Instagram, and LinkedIn",
            "Create engaging posts and coordinate with the design team",
            "Engage with followers and manage community responses",
            "Report on growth metrics and refine strategy monthly",
        ],
        qualifications: [
            "Experience managing social media accounts for a brand",
            "Creative writing and basic graphic design skills",
            "Familiarity with scheduling tools (Buffer, Hootsuite)",
            "Understanding of social media analytics",
        ],
    },
    {
        id: 12,
        applicantName: "Emeka Okonkwo",
        isVerified: true,
        rating: 5,
        ratingCount: 5.0,
        timePosted: "1 month ago",
        jobTitle: "Full Stack Developer - FinTech Solution",
        salaryRange: "₦500,000 - ₦800,000",
        description:
            "We are building a next-gen fintech platform and need a full stack developer. You will work on both frontend and backend, integrating payment gateways and ensuring security compliance.",
        tags: ["Senior", "Hybrid", "3 months"],
        views: 72,
        status: "Shortlisted",
        location: "Lagos, Nigeria (Hybrid)",
        experience: "5+ years",
        deadline: "Mar 15, 2026",
        responsibilities: [
            "Build and maintain frontend dashboards with React/Next.js",
            "Develop secure backend APIs with Node.js and Express",
            "Integrate payment providers (Paystack, Stripe)",
            "Ensure the platform meets PCI-DSS security standards",
        ],
        qualifications: [
            "Full stack experience across React and Node.js",
            "Prior experience in fintech or payment integrations",
            "Strong security mindset and awareness of OWASP top 10",
            "Ability to work in a fast-paced startup environment",
        ],
    },
    {
        id: 13,
        applicantName: "Adaeze Igwe",
        isVerified: false,
        rating: 2,
        ratingCount: 2.8,
        timePosted: "1 month ago",
        jobTitle: "Graphic Designer - Brand Identity",
        salaryRange: "₦120,000 - ₦180,000",
        description:
            "We need a graphic designer to help define our brand identity. You will create logos, marketing materials, and social media assets that reflect our modern and approachable brand voice.",
        tags: ["Entry-level", "Remote", "2 weeks"],
        views: 15,
        status: "Rejected",
        location: "Nationwide (Remote)",
        experience: "1+ year",
        deadline: "Feb 25, 2026",
        responsibilities: [
            "Design logo variations and brand guidelines document",
            "Create templates for social media, email, and print",
            "Ensure visual consistency across all brand touchpoints",
            "Incorporate client feedback through revision cycles",
        ],
        qualifications: [
            "Proficient in Adobe Creative Suite or Canva Pro",
            "Portfolio showing brand identity projects",
            "Strong sense of visual hierarchy and layout",
            "Good at taking and incorporating feedback",
        ],
    },
    {
        id: 14,
        applicantName: "Kalu Obi",
        isVerified: true,
        rating: 4,
        ratingCount: 4.1,
        timePosted: "6 weeks ago",
        jobTitle: "Project Manager - Agile Teams",
        salaryRange: "₦300,000 - ₦420,000",
        description:
            "Looking for a project manager experienced in Agile methodologies to coordinate cross-functional teams. You will manage timelines, facilitate sprints, and ensure project delivery.",
        tags: ["Mid-level", "On-site", "Ongoing"],
        views: 31,
        status: null,
        location: "Abuja, Nigeria (On-site)",
        experience: "3+ years",
        deadline: "Ongoing",
        responsibilities: [
            "Facilitate daily standups, sprint planning, and retrospectives",
            "Manage project timelines and resource allocation",
            "Serve as the primary liaison between stakeholders and dev teams",
            "Identify and mitigate project risks proactively",
        ],
        qualifications: [
            "PMP or Scrum Master certification preferred",
            "3+ years managing software development projects",
            "Excellent communication and leadership skills",
            "Experience with Jira, Asana, or similar PM tools",
        ],
    },
    {
        id: 15,
        applicantName: "Ngozi Achike",
        isVerified: true,
        rating: 3,
        ratingCount: 3.6,
        timePosted: "2 months ago",
        jobTitle: "Copywriter - Ad Campaign",
        salaryRange: "₦90,000 - ₦130,000",
        description:
            "We need a copywriter to craft compelling ad copy for an upcoming campaign. You will work with the creative team to develop messaging that drives engagement and conversions.",
        tags: ["Entry-level", "Remote", "1 week"],
        views: 10,
        status: "Rejected",
        location: "Nationwide (Remote)",
        experience: "1+ year",
        deadline: "Feb 12, 2026",
        responsibilities: [
            "Write ad copy for Google, Facebook, and Instagram campaigns",
            "Develop landing page headlines and CTAs",
            "A/B test copy variations and analyze performance",
            "Align messaging with the broader brand voice guidelines",
        ],
        qualifications: [
            "Strong persuasive writing skills",
            "Experience with digital advertising copy",
            "Basic understanding of marketing funnels",
            "Ability to deliver polished work under tight deadlines",
        ],
    },
];