export const walletData = {
    balance: "21,000,000.12",
    pendingPayment: "500,000.00",
    totalEarnings: "2,450,000",
    pendingPaymentAmount: "500,000",
};

export const payments = [
    {
        id: 1,
        jobTitle: "Product Designer",
        company: "Moniepoint",
        avatar: "https://i.pravatar.cc/150?img=1",
        amount: "2,450,000",
        status: "Pending", // "Pending" | "Paid" | "Rejected"
        date: "12/08/2025",
        // Details for modal
        from: "Moniepoint",
        gig: "Product Designer",
        reference: "Reference",
        statusDetail: "Successful",
    },
    {
        id: 2,
        jobTitle: "Product Designer",
        company: "Onpoint lab",
        avatar: "https://i.pravatar.cc/150?img=2",
        amount: "50,000",
        status: "Paid",
        date: "10/08/2025",
        from: "Onpoint lab",
        gig: "Product Designer",
        reference: "PAY-2024-08-10-001",
        statusDetail: "Completed",
    },
    {
        id: 3,
        jobTitle: "Product Designer",
        company: "Moniepoint",
        avatar: "https://i.pravatar.cc/150?img=3",
        amount: "45,000",
        status: "Rejected",
        date: "4/08/2025",
        from: "Moniepoint",
        gig: "Product Designer",
        reference: "PAY-2024-08-04-002",
        statusDetail: "Declined",
    },
    {
        id: 4,
        jobTitle: "UI/UX Designer",
        company: "Moniepoint",
        avatar: "https://i.pravatar.cc/150?img=4",
        amount: "500,000",
        status: "Pending",
        date: "1/08/2025",
        from: "Moniepoint",
        gig: "UI/UX Designer",
        reference: "PAY-2024-08-01-003",
        statusDetail: "Processing",
    },
    {
        id: 5,
        jobTitle: "UI/UX Developer",
        company: "Moniepoint",
        avatar: "https://i.pravatar.cc/150?img=5",
        amount: "400,000",
        status: "Rejected",
        date: "25/07/2025",
        from: "Moniepoint",
        gig: "UI/UX Developer",
        reference: "PAY-2024-07-25-004",
        statusDetail: "Declined",
    },
    {
        id: 6,
        jobTitle: "Product Designer",
        company: "Moniepoint",
        avatar: "https://i.pravatar.cc/150?img=6",
        amount: "600,000",
        status: "Paid",
        date: "12/08/2025",
        from: "Moniepoint",
        gig: "Product Designer",
        reference: "PAY-2024-08-12-005",
        statusDetail: "Completed",
    },
    {
        id: 7,
        jobTitle: "Creative Designer",
        company: "Moniepoint",
        avatar: "https://i.pravatar.cc/150?img=7",
        amount: "950,000",
        status: "Paid",
        date: "06/08/2025",
        from: "Moniepoint",
        gig: "Creative Designer",
        reference: "PAY-2024-08-06-006",
        statusDetail: "Completed",
    },
    {
        id: 8,
        jobTitle: "Product Designer",
        company: "Moniepoint",
        avatar: "https://i.pravatar.cc/150?img=8",
        amount: "2,550,000",
        status: "Paid",
        date: "12/08/2025",
        from: "Moniepoint",
        gig: "Product Designer",
        reference: "PAY-2024-08-12-007",
        statusDetail: "Completed",
    },
    {
        id: 9,
        jobTitle: "Frontend Developer",
        company: "TechCorp",
        avatar: "https://i.pravatar.cc/150?img=9",
        amount: "750,000",
        status: "Pending",
        date: "15/08/2025",
        from: "TechCorp",
        gig: "Frontend Developer",
        reference: "PAY-2024-08-15-008",
        statusDetail: "Processing",
    },
    {
        id: 10,
        jobTitle: "Backend Engineer",
        company: "DevHub",
        avatar: "https://i.pravatar.cc/150?img=10",
        amount: "1,200,000",
        status: "Paid",
        date: "18/08/2025",
        from: "DevHub",
        gig: "Backend Engineer",
        reference: "PAY-2024-08-18-009",
        statusDetail: "Completed",
    },
    {
        id: 11,
        jobTitle: "Mobile Developer",
        company: "AppWorks",
        avatar: "https://i.pravatar.cc/150?img=11",
        amount: "850,000",
        status: "Rejected",
        date: "20/08/2025",
        from: "AppWorks",
        gig: "Mobile Developer",
        reference: "PAY-2024-08-20-010",
        statusDetail: "Declined",
    },
    {
        id: 12,
        jobTitle: "Data Analyst",
        company: "DataFlow",
        avatar: "https://i.pravatar.cc/150?img=12",
        amount: "550,000",
        status: "Paid",
        date: "22/08/2025",
        from: "DataFlow",
        gig: "Data Analyst",
        reference: "PAY-2024-08-22-011",
        statusDetail: "Completed",
    },
    {
        id: 13,
        jobTitle: "DevOps Engineer",
        company: "CloudOps",
        avatar: "https://i.pravatar.cc/150?img=13",
        amount: "1,500,000",
        status: "Pending",
        date: "25/08/2025",
        from: "CloudOps",
        gig: "DevOps Engineer",
        reference: "PAY-2024-08-25-012",
        statusDetail: "Processing",
    },
    {
        id: 14,
        jobTitle: "QA Engineer",
        company: "TestLabs",
        avatar: "https://i.pravatar.cc/150?img=14",
        amount: "450,000",
        status: "Paid",
        date: "28/08/2025",
        from: "TestLabs",
        gig: "QA Engineer",
        reference: "PAY-2024-08-28-013",
        statusDetail: "Completed",
    },
    {
        id: 15,
        jobTitle: "Full Stack Developer",
        company: "WebSolutions",
        avatar: "https://i.pravatar.cc/150?img=15",
        amount: "1,800,000",
        status: "Rejected",
        date: "30/08/2025",
        from: "WebSolutions",
        gig: "Full Stack Developer",
        reference: "PAY-2024-08-30-014",
        statusDetail: "Declined",
    },
];